// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/lin-snow/ech0/internal/cache"
	"github.com/lin-snow/ech0/internal/event"
	"github.com/lin-snow/ech0/internal/fediverse"
	handler12 "github.com/lin-snow/ech0/internal/handler/agent"
	handler9 "github.com/lin-snow/ech0/internal/handler/backup"
	handler4 "github.com/lin-snow/ech0/internal/handler/common"
	handler8 "github.com/lin-snow/ech0/internal/handler/connect"
	handler11 "github.com/lin-snow/ech0/internal/handler/dashboard"
	handler3 "github.com/lin-snow/ech0/internal/handler/echo"
	handler10 "github.com/lin-snow/ech0/internal/handler/fediverse"
	handler6 "github.com/lin-snow/ech0/internal/handler/inbox"
	handler5 "github.com/lin-snow/ech0/internal/handler/setting"
	handler7 "github.com/lin-snow/ech0/internal/handler/todo"
	handler2 "github.com/lin-snow/ech0/internal/handler/user"
	"github.com/lin-snow/ech0/internal/handler/web"
	"github.com/lin-snow/ech0/internal/metric"
	"github.com/lin-snow/ech0/internal/monitor"
	repository2 "github.com/lin-snow/ech0/internal/repository/common"
	repository9 "github.com/lin-snow/ech0/internal/repository/connect"
	repository3 "github.com/lin-snow/ech0/internal/repository/echo"
	repository6 "github.com/lin-snow/ech0/internal/repository/fediverse"
	repository7 "github.com/lin-snow/ech0/internal/repository/inbox"
	"github.com/lin-snow/ech0/internal/repository/keyvalue"
	repository10 "github.com/lin-snow/ech0/internal/repository/queue"
	repository4 "github.com/lin-snow/ech0/internal/repository/setting"
	repository8 "github.com/lin-snow/ech0/internal/repository/todo"
	"github.com/lin-snow/ech0/internal/repository/user"
	repository5 "github.com/lin-snow/ech0/internal/repository/webhook"
	service11 "github.com/lin-snow/ech0/internal/service/agent"
	service9 "github.com/lin-snow/ech0/internal/service/backup"
	"github.com/lin-snow/ech0/internal/service/common"
	service8 "github.com/lin-snow/ech0/internal/service/connect"
	service10 "github.com/lin-snow/ech0/internal/service/dashboard"
	service5 "github.com/lin-snow/ech0/internal/service/echo"
	service4 "github.com/lin-snow/ech0/internal/service/fediverse"
	service6 "github.com/lin-snow/ech0/internal/service/inbox"
	service2 "github.com/lin-snow/ech0/internal/service/setting"
	service7 "github.com/lin-snow/ech0/internal/service/todo"
	service3 "github.com/lin-snow/ech0/internal/service/user"
	"github.com/lin-snow/ech0/internal/task"
	"github.com/lin-snow/ech0/internal/transaction"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// BuildHandlers 使用wire生成的代码来构建Handlers实例
func BuildHandlers(dbProvider func() *gorm.DB, cacheFactory *cache.CacheFactory, tmFactory *transaction.TransactionManagerFactory, ebProvider func() event.IEventBus) (*Handlers, error) {
	webHandler := handler.NewWebHandler()
	transactionManager := ProvideTransactionManager(tmFactory)
	iCache := ProvideCache(cacheFactory)
	userRepositoryInterface := repository.NewUserRepository(dbProvider, iCache)
	commonRepositoryInterface := repository2.NewCommonRepository(dbProvider)
	echoRepositoryInterface := repository3.NewEchoRepository(dbProvider, iCache)
	keyValueRepositoryInterface := keyvalue.NewKeyValueRepository(dbProvider, iCache)
	commonServiceInterface := service.NewCommonService(transactionManager, commonRepositoryInterface, echoRepositoryInterface, keyValueRepositoryInterface, ebProvider)
	settingRepositoryInterface := repository4.NewSettingRepository(dbProvider)
	webhookRepositoryInterface := repository5.NewWebhookRepository(dbProvider)
	settingServiceInterface := service2.NewSettingService(transactionManager, commonServiceInterface, keyValueRepositoryInterface, settingRepositoryInterface, webhookRepositoryInterface, ebProvider)
	userServiceInterface := service3.NewUserService(transactionManager, userRepositoryInterface, settingServiceInterface, ebProvider)
	userHandler := handler2.NewUserHandler(userServiceInterface)
	fediverseRepositoryInterface := repository6.NewFediverseRepository(dbProvider)
	fediverseCore := fediverse.NewFediverseCore(fediverseRepositoryInterface, keyValueRepositoryInterface, userRepositoryInterface, echoRepositoryInterface)
	fediverseServiceInterface := service4.NewFediverseService(fediverseCore, transactionManager, fediverseRepositoryInterface, userRepositoryInterface, echoRepositoryInterface)
	echoServiceInterface := service5.NewEchoService(transactionManager, commonServiceInterface, echoRepositoryInterface, commonRepositoryInterface, fediverseServiceInterface, keyValueRepositoryInterface, ebProvider)
	echoHandler := handler3.NewEchoHandler(echoServiceInterface)
	commonHandler := handler4.NewCommonHandler(commonServiceInterface)
	settingHandler := handler5.NewSettingHandler(settingServiceInterface)
	inboxRepositoryInterface := repository7.NewInboxRepository(dbProvider)
	inboxServiceInterface := service6.NewInboxService(transactionManager, commonServiceInterface, inboxRepositoryInterface)
	inboxHandler := handler6.NewInboxHandler(inboxServiceInterface)
	todoRepositoryInterface := repository8.NewTodoRepository(dbProvider, iCache)
	todoServiceInterface := service7.NewTodoService(transactionManager, todoRepositoryInterface, commonServiceInterface)
	todoHandler := handler7.NewTodoHandler(todoServiceInterface)
	connectRepositoryInterface := repository9.NewConnectRepository(dbProvider)
	connectServiceInterface := service8.NewConnectService(transactionManager, connectRepositoryInterface, echoRepositoryInterface, commonServiceInterface, settingServiceInterface)
	connectHandler := handler8.NewConnectHandler(connectServiceInterface)
	backupServiceInterface := service9.NewBackupService(commonServiceInterface, ebProvider)
	backupHandler := handler9.NewBackupHandler(backupServiceInterface)
	fediverseHandler := handler10.NewFediverseHandler(fediverseServiceInterface)
	metricCollector := metric.NewSystemCollector()
	monitorMonitor := monitor.NewMonitor(metricCollector)
	dashboardServiceInterface := service10.NewDashboardService(monitorMonitor, commonServiceInterface)
	dashboardHandler := handler11.NewDashboardHandler(dashboardServiceInterface)
	agentServiceInterface := service11.NewAgentService(settingServiceInterface, echoServiceInterface, todoServiceInterface, keyValueRepositoryInterface)
	agentHandler := handler12.NewAgentHandler(agentServiceInterface)
	handlers := NewHandlers(webHandler, userHandler, echoHandler, commonHandler, settingHandler, inboxHandler, todoHandler, connectHandler, backupHandler, fediverseHandler, dashboardHandler, agentHandler)
	return handlers, nil
}

func BuildTasker(dbProvider func() *gorm.DB, cacheFactory *cache.CacheFactory, tmFactory *transaction.TransactionManagerFactory, ebProvider func() event.IEventBus) (*task.Tasker, error) {
	transactionManager := ProvideTransactionManager(tmFactory)
	commonRepositoryInterface := repository2.NewCommonRepository(dbProvider)
	iCache := ProvideCache(cacheFactory)
	echoRepositoryInterface := repository3.NewEchoRepository(dbProvider, iCache)
	keyValueRepositoryInterface := keyvalue.NewKeyValueRepository(dbProvider, iCache)
	commonServiceInterface := service.NewCommonService(transactionManager, commonRepositoryInterface, echoRepositoryInterface, keyValueRepositoryInterface, ebProvider)
	settingRepositoryInterface := repository4.NewSettingRepository(dbProvider)
	webhookRepositoryInterface := repository5.NewWebhookRepository(dbProvider)
	settingServiceInterface := service2.NewSettingService(transactionManager, commonServiceInterface, keyValueRepositoryInterface, settingRepositoryInterface, webhookRepositoryInterface, ebProvider)
	queueRepositoryInterface := repository10.NewQueueRepository(dbProvider)
	tasker := task.NewTasker(commonServiceInterface, settingServiceInterface, ebProvider, queueRepositoryInterface)
	return tasker, nil
}

func BuildEventRegistrar(dbProvider func() *gorm.DB, ebProvider func() event.IEventBus, cacheFactory *cache.CacheFactory, tmFactory *transaction.TransactionManagerFactory) (*event.EventRegistrar, error) {
	webhookRepositoryInterface := repository5.NewWebhookRepository(dbProvider)
	queueRepositoryInterface := repository10.NewQueueRepository(dbProvider)
	transactionManager := ProvideTransactionManager(tmFactory)
	webhookDispatcher := event.NewWebhookDispatcher(ebProvider, webhookRepositoryInterface, queueRepositoryInterface, transactionManager)
	fediverseRepositoryInterface := repository6.NewFediverseRepository(dbProvider)
	iCache := ProvideCache(cacheFactory)
	keyValueRepositoryInterface := keyvalue.NewKeyValueRepository(dbProvider, iCache)
	userRepositoryInterface := repository.NewUserRepository(dbProvider, iCache)
	echoRepositoryInterface := repository3.NewEchoRepository(dbProvider, iCache)
	fediverseCore := fediverse.NewFediverseCore(fediverseRepositoryInterface, keyValueRepositoryInterface, userRepositoryInterface, echoRepositoryInterface)
	fediverseAgent := event.NewFediverseAgent(fediverseCore, queueRepositoryInterface, transactionManager)
	deadLetterResolver := event.NewDeadLetterResolver(queueRepositoryInterface, webhookDispatcher, fediverseAgent)
	backupScheduler := event.NewBackupScheduler()
	todoRepositoryInterface := repository8.NewTodoRepository(dbProvider, iCache)
	inboxRepositoryInterface := repository7.NewInboxRepository(dbProvider)
	agentProcessor := event.NewAgentProcessor(echoRepositoryInterface, todoRepositoryInterface, userRepositoryInterface, keyValueRepositoryInterface, inboxRepositoryInterface)
	eventHandlers := event.NewEventHandlers(webhookDispatcher, deadLetterResolver, fediverseAgent, backupScheduler, agentProcessor)
	eventRegistrar := event.NewEventRegistry(ebProvider, eventHandlers)
	return eventRegistrar, nil
}

// wire.go:

// CacheSet 包含了构建缓存所需的所有 Provider
var CacheSet = wire.NewSet(
	ProvideCache,
)

// TransactionManagerSet 包含了构建事务管理器所需的所有 Provider
var TransactionManagerSet = wire.NewSet(
	ProvideTransactionManager,
)

// WebSet 包含了构建 WebHandler 所需的所有 Provider
var WebSet = wire.NewSet(handler.NewWebHandler)

// UserSet 包含了构建 UserHandler 所需的所有 Provider
var UserSet = wire.NewSet(repository.NewUserRepository, service3.NewUserService, handler2.NewUserHandler)

// EchoSet 包含了构建 EchoHandler 所需的所有 Provider
var EchoSet = wire.NewSet(repository3.NewEchoRepository, service5.NewEchoService, handler3.NewEchoHandler)

// CommonSet 包含了构建 CommonHandler 所需的所有 Provider
var CommonSet = wire.NewSet(repository2.NewCommonRepository, service.NewCommonService, handler4.NewCommonHandler)

// KeyValueSet 包含了构建 KeyValueRepository 所需的所有 Provider
var KeyValueSet = wire.NewSet(keyvalue.NewKeyValueRepository)

// SettingSet 包含了构建 SettingHandler 所需的所有 Provider
var SettingSet = wire.NewSet(repository4.NewSettingRepository, service2.NewSettingService, handler5.NewSettingHandler)

// TodoSet 包含了构建 TodoHandler 所需的所有 Provider
var TodoSet = wire.NewSet(repository8.NewTodoRepository, service7.NewTodoService, handler7.NewTodoHandler)

// ConnectSet 包含了构建 ConnectHandler 所需的所有 Provider
var ConnectSet = wire.NewSet(repository9.NewConnectRepository, service8.NewConnectService, handler8.NewConnectHandler)

// BackupSet 包含了构建 BackupHandler 所需的所有 Provider
var BackupSet = wire.NewSet(handler9.NewBackupHandler, service9.NewBackupService)

// DashboardSet 包含了构建 DashboardHandler 所需的所有 Provider
var DashboardSet = wire.NewSet(service10.NewDashboardService, handler11.NewDashboardHandler)

// AgentSet 包含了构建 AgentHandler 所需的所有 Provider
var AgentSet = wire.NewSet(service11.NewAgentService, handler12.NewAgentHandler)

// WebhookSet 包含了构建 WebhookDispatcher 所需的所有 Provider
var WebhookSet = wire.NewSet(repository5.NewWebhookRepository)

// InboxSet 包含了构建 InboxRepository 所需的所有 Provider
var InboxSet = wire.NewSet(repository7.NewInboxRepository, service6.NewInboxService, handler6.NewInboxHandler)

// TaskSet 包含了构建 Tasker 所需的所有 Provider
var TaskSet = wire.NewSet(task.NewTasker)

// QueueSet 包含了构建 Queue 所需的所有 Provider
var QueueSet = wire.NewSet(repository10.NewQueueRepository)

// FediverseCoreSet 包含了构建 FediverseCore 所需的所有 Provider
var FediverseCoreSet = wire.NewSet(fediverse.NewFediverseCore)

// FediverseSet 包含了构建 Fediverse 所需的所有 Provider
var FediverseSet = wire.NewSet(repository6.NewFediverseRepository, service4.NewFediverseService, handler10.NewFediverseHandler, event.NewFediverseAgent)

// EventSet 包含了构建 Event 相关所需的所有 Provider
var EventSet = wire.NewSet(event.NewWebhookDispatcher, event.NewBackupScheduler, event.NewDeadLetterResolver, event.NewAgentProcessor, event.NewEventHandlers, event.NewEventRegistry)

// MetricSet 包含了构建 Metric 相关所需的所有 Provider
var MetricSet = wire.NewSet(metric.NewSystemCollector)

// MonitorSet 包含了构建 Monitor 相关所需的所有 Provider
var MonitorSet = wire.NewSet(monitor.NewMonitor)
